### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by flexeykinDev** [emp0ry/CSGO-RGB-Crosshair-without-Cheats#1]
My friend used slow rgb, also run programm as a administrator.
and after one cycle at red color program got crashed. (or after one round)
Resolution 1024x768

**Comment by emp0ry** [comment]
Everything works fine for me. add in code try except

**Comment by emp0ry** [comment]
Everything works fine for me and my friends, maybe he has a weak PC or crooked Windows is worth. Screen resolution doesn't change anything, should work on any resolution.
